name: 'Continuous Deployment'

on:
  workflow_run:
    workflows: ['Continuous Integration']
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    branches: [main]
    types:
      - completed
jobs:
  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: build
      - name: rename folder
        run: |
          cp build/index.html build/404.html
          mv build docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 
