name: 'Continuous Deployment'

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches: [main]
    types:
      - completed

jobs:
  gh-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          name: frontend-build
          path: build
      - name: rename folder
        run: |
          cp build/index.html build/404.html
          mv build docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 
