name: "Continuous Integration"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: "install dependencies"
        run: yarn install
      - name: "check translations"
        run: yarn check:i18n
  build:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: "install dependencies"
        run: yarn install
      - name: "run build"
        run: yarn build
      - name: Add artifact to github
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: build